### ISSUE TITLE
client side extraction with useragent?

### ISSUE THREAD

**Issue by netconstructor** [nrabinowitz/pjscrape#14]
I am trying to figure out if this script can run indipendently on a users browser. By this I mean, could a url be entered into the browder by any browser which in effect could execute the scrape using the users IP all without communicating back to a central host server?

Additionally, can one specifiy variables such as custom user agents and dns to be utilized when such requests are made?

**Comment by nrabinowitz** [comment]
I'm not sure I entirely understand the question. Pjscrape is built to run on PhantomJS, which _is_ a browser - a headless browser that runs on the command line. I've built out a minimal version you can run in a normal browser through [a bookmarklet](http://nrabinowitz.github.com/pjscrape/#bookmarklet), but this is really just for testing - it can only output to the Javascript console, and it can't scrape multiple pages (because it would need to be reloaded each time).

The question about user agent is a good one. PhantomJS provides support for this, but it's hard to access through Pjscrape - I think this should be easy once I've implemented issue #4.

**Comment by netconstructor** [comment]
i think i understand the logic of you script... let me ask a followup question. Are you aware of any way one would be able to scrape the content being loaded in on a page from an iframe off a different domain? I am thinking there bust be some work arround to this using a headless browser.

Finally, have you conducted any comparisions of PhantomJS compared to other solutions?

**Comment by nrabinowitz** [comment]
The problem of scraping content in an iframe isn't really one that a headless browser helps with:
- If you're using PhantomJS, you don't need to work with an iframe, you can access and scrape the site directly - but only within the PhantomJS browser, which runs from the command line and doesn't have a GUI.
- If you're using a standard browser, you're dealing with a whole different set of issues, and there's no good way to make PhantomJS interact with the browser you're using.

There are a number of other options, but PhantomJS is the only one I'm aware of that a) gives you a full browser context, including executing AJAX requests and other scripts, and b) doesn't involve the overhead of controlling a standard browser. Other options on either side of this:
- There are plenty of language-specific libraries to download HTML, parse it, and scrape it. Python has Mechanize, scrapy, BeautifulSoup, and several others. Ruby has Hpricot and I'm sure others I don't know. Node.js has jsdom and Zombie.js (though I couldn't get them running on Windows). These are all good solutions if you only need the basic HTML text and you're willing to futz around with Xpath or custom selectors. Jsdom can use jQuery, and might be an increasingly good option, but it's not a real browser.
- On the other side, Selenium and maybe iMacros are heavyweight, full-browser automation systems, requiring a full running browser. They give you an absolutely accurate browser context, but they're slow and a pain to script.

PhantomJS seems to hit a sweet spot in the middle, giving you 98% of a real browser with more speed, less overhead, and a simple and lightweight scripting approach.

...happy to continue this offline, but I'm going to close this issue, as I don't think your requirements are really within the scope of this project.
