### ISSUE TITLE
ERROR: Page did not load (status=fail)

### ISSUE THREAD

**Issue by christianhellsten** [nrabinowitz/pjscrape#16]
I'm getting "ERROR: Page did not load (status=fail):" errors with PhantomJS 1.5 and the latest version of pjscrape:

```
$ phantomjs --load-images=no --web-security=no --ignore-ssl-errors=yes --disk-cache=yes --cookies-file=/tmp/cookies.txt --load-plugins=yes pjscrape-head.js cnn.js 
* Suite 0 starting
* Opening http://www.cnn.com
* Scraping http://www.cnn.com
TypeError: 'null' is not an object

  phantomjs://webpage.evaluate():4
  phantomjs://webpage.evaluate():1
  pjscrape-head.js:723
  pjscrape-head.js:720
  pjscrape-head.js:488
* Found 215 additional urls to scrape
* Suite 0 complete
* Suite 0-sub0 starting
* Opening http://edition.cnn.com/
ERROR: Page did not load (status=fail): http://edition.cnn.com/
```

Looks similar to this issue, but I'm sure the Content-Type header is available:
http://code.google.com/p/phantomjs/issues/detail?id=128
https://github.com/ariya/phantomjs/pull/135

Here's the code I'm using:

```
var scraper = function() {
  var links = $('a')
  links = links.map(function(index, elem) { 
    return $(elem).text()
  }).toArray()
  return links
}

pjs.addSuite({
  url: 'http://www.cnn.com',
  maxDepth: 1,
  noConflict: true,
  moreUrls: function() {
    return _pjs.getAnchorUrls('a', false)
  },
  scraper: scraper
});
```

Adding some debug code I see that status and statusText are null:

```
* Opening http://edition.cnn.com/cnni/
received: {
    "contentType": null,
    "headers": [],
    "id": 220,
    "redirectURL": null,
    "stage": "end",
    "status": null,
    "statusText": null,
    "time": "2012-05-20T08:05:14.977Z",
    "url": "http://edition.cnn.com/CNNI/"
}
ERROR: Page did not load (status=fail): http://edition.cnn.com/cnni/
```

Note that removing the noConflict option fixes the "TypeError: 'null' is not an object" issue.

**Comment by nrabinowitz** [comment]
The `noConflict` option doesn't guarantee that `$` will be the Pjscrape jQuery variable. When using `noConflict`, you need to use `_pjs.$` instead of `$` as your jQuery reference (I wish there was a better way around this, but there isn't as far as I can tell). This should fix the initial JavaScript errors.

I can replicate the `status=fail` errors, but I think this is probably server-specific - perhaps CNN.com is recognizing and preventing automated scrapers from accessing more than one page.

**Comment by christianhellsten** [comment]
Yes, that's what I was thinking too. I tried making pjscrape crawl slower to prevent any such issues, but I didn't find any quick way of doing it. phantomjs.sleep no longer exists…

**Comment by nrabinowitz** [comment]
You could set a timeout in your scraper itself - see https://github.com/nrabinowitz/pjscrape/blob/master/tests/test_async.js for syntax. Just use `setTimeout()` and then set `_pjs.items` in your timeout callback.
