### ISSUE TITLE
undefined:29 TypeError: Result of expression 'phantom.injectJs' [undefined] is not a function. 

### ISSUE THREAD

**Issue by brunoamaral** [nrabinowitz/pjscrape#2]
I get the above error message when i try to run the tutorial on the readme file.

This happens on a Mac with Snow Leopard running phantomjs.

Don't rule out that this may be a problem on my side.

**Comment by nrabinowitz** [comment]
What version of PhantomJS are you running? I don't think the .injectJS
method was introduced until v.1.2, so that version is a prerequisite. The
error you're getting seems to imply that the function isn't available in
your version.

-Nick

**Comment by brunoamaral** [comment]
You're right Nick, thank you! 

I had installed phantomjs with brew and it was still listing version 1.1.

May be a good idea to include this information on the readme file.

**Comment by nrabinowitz** [comment]
Thanks, I'll add the dependencies to the README.
