### ISSUE TITLE
Saving JSON to external file

### ISSUE THREAD

**Issue by crazy4groovy** [nrabinowitz/pjscrape#22]
How do I specify and export scraped data into a file instead printing to the screen? Would be nice to have in documentation. I am using PhantomJS 1.6. Thanks!

**Comment by nrabinowitz** [comment]
There are two easy ways to do this:
1. Redirect STDOUT to a file:
   
   ```
   ~> phantomjs pjscrape.js my_script.js > my_output.json
   ```
2. Use the `"file"` writer and set the `outFile` config parameter: see https://github.com/nrabinowitz/pjscrape/blob/master/tests/file_output_config.js

I'll try to add to the docs - haven't had much chance to update lately.

**Comment by crazy4groovy** [comment]
I knew about 1., but 2. is great. Thanks!
