### ISSUE TITLE
Can't get the itemfile or file writers to work 

### ISSUE THREAD

**Issue by simonexmachina** [nrabinowitz/pjscrape#24]
I've read the docs and checked the code, but the following config doesn't result in a file being written. I'm using the latest version of PhantomJS (1.6.1) and master branch of pjscrape (0.1.4 in VERSION.txt)

```
pjs.addSuite({
  url: 'http://www.google.com/',
  writer: 'itemfile',
  // outFile: '/tmp/pjscrape-out.txt',
  scraper: function() {
    return {
      filename: '/tmp/pjscrape-out.txt',
      content: document.documentElement.outerHTML
    }
  }
});
```

I've also tried 'file' writer and outFile in the top-level config, but neither results in a file being written.

**Comment by nrabinowitz** [comment]
Writers and loggers can't be set in `.addSuite()` - they need to be specified in `.config()`:

```
pjs.config({
  writer: 'itemfile',
});

pjs.addSuite({
  url: 'http://www.google.com/',
  scraper: function() {
    return {
      filename: 'pjscrape-out.txt',
      content: document.documentElement.outerHTML
    }
  }
});
```

**Comment by simonexmachina** [comment]
Awesome, thanks Nick.
