### ISSUE TITLE
Calling pjscrape via commandline and append Results to File

### ISSUE THREAD

**Issue by dasraab** [nrabinowitz/pjscrape#59]
Is there any to call pjscrape via commandline? like pjscrape.sh my_config.json "http://myurl.org" and append the results to a file? 

i´ve to scrape thousends of similar sites (only id in url changes). all those urls are saved in a database.... so cli-call would be perfect...

thanks for your help! great project!

**Comment by nrabinowitz** [comment]
Have you read the docs? It's a command line tool, that's the whole point... Take a look at the readme and let me know if you still have questions...

**Comment by dasraab** [comment]
yes i´ve read the docs... the main question is how i can set the url that has to be crawled by commandline call... can you give me a hint?

**Comment by LunarDevelopment** [comment]
Poor form from owner on not answering this.

"Here's some code, no I'm not telling you how to use it."
