### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sunshineo** [nrabinowitz/pjscrape#65]
Sorry to be so straight, but the last update is a year ago and here we have a lot of issues coming in.
Has the author gave up on this project? Is there any alternative you recommend?

I found https://www.npmjs.com/package/jedi-crawler https://www.npmjs.com/package/console-crawler https://www.npmjs.com/package/spa-crawler
But they also have not been updated for a while. (BTW, can this be put on NPM?)

There are a lot of stuff at https://www.npmjs.com/search?q=crawler&page=2 but I feel I should pick something built on top of phantomjs or another headless browser to not limit myself.
What do you think? Thank you very much!

**Comment by nrabinowitz** [comment]
It's not dead, it's sleeping. It's [pining for the fjords](https://www.youtube.com/watch?v=4vuW6tQ0218) :).

In all seriousness, I've let the project lapse for a while, and don't intend to add major features, but I am intending to package it for npm and tidy up a few issues.

**Comment by awebdeveloper** [comment]
any alternatives you would recommend
